Repository benavlabs/FastAPI-boilerplate, pull requests merged in 2023-12, with the labels that each got.

#65 Folder structure
  Dockerfile
  README.md
  docker-compose.yml
  pyproject.toml
  src/app/api/__init__.py
  src/app/api/dependencies.py
  src/app/api/v1/__init__.py
  src/app/api/v1/login.py
  src/app/api/v1/logout.py
  src/app/api/v1/posts.py
  src/app/api/v1/rate_limits.py
  src/app/api/v1/tasks.py
  src/app/api/v1/tiers.py
  src/app/api/v1/users.py
  src/app/core/config.py
  src/app/core/db/crud_token_blacklist.py
  src/app/core/db/database.py
  src/app/core/db/token_blacklist.py
  src/app/core/security.py
  src/app/core/setup.py
  src/app/core/utils/cache.py
  src/app/core/utils/rate_limit.py
  src/app/crud/crud_base.py
  src/app/crud/crud_posts.py
  src/app/crud/crud_rate_limit.py
  src/app/crud/crud_tier.py
  src/app/crud/crud_users.py
  src/app/crud/helper.py
  src/app/main.py
  src/app/models/post.py
  src/app/models/rate_limit.py
  src/app/models/tier.py
  src/app/models/user.py
  src/app/schemas/post.py
  src/app/schemas/rate_limit.py
  src/app/schemas/tier.py
  src/app/schemas/user.py
  src/app/worker.py
  src/scripts/create_first_superuser.py
  src/scripts/create_first_tier.py
  tests/__init__.py
  tests/conftest.py
  tests/helper.py
  tests/test_user.py
Labels: enhancement

#66 pagination bug fixed
  src/app/api/paginated.py
  src/app/api/v1/posts.py
  src/app/api/v1/rate_limits.py
  src/app/api/v1/tiers.py
  src/app/api/v1/users.py
Labels: bug

#69 config.py port datatype consistency
  src/app/core/config.py
Labels: enhancement

#71 commented non essential services in docker compose
  docker-compose.yml
Labels: bug

#72 pydantic validators migrated to v2
  src/app/schemas/rate_limit.py
Labels: bug

#73 added return type hint to rate limit validator
  src/app/schemas/rate_limit.py
Labels: bug

#74 passlib replaced with bcrypt for password hashing
  pyproject.toml
  src/app/api/dependencies.py
  src/app/core/security.py
Labels: bug

#78 Update README.md
  README.md
Labels: documentation

#81 CRUDBase count method bug fix
  src/app/core/security.py
  src/app/crud/crud_base.py
Labels: bug

#80 Refactor datetime.utcnow() to datetime.now(timezone.utc)
  README.md
  src/app/core/db/models.py
  src/app/core/schemas.py
  src/app/core/security.py
  src/app/core/utils/rate_limit.py
  src/app/crud/crud_base.py
  src/app/models/post.py
  src/app/models/rate_limit.py
  src/app/models/tier.py
  src/app/models/user.py
  src/scripts/create_first_superuser.py
Labels: enhancement

#82 79 datetimeutcnow is deprecated as of python 312
  README.md
  src/app/core/db/models.py
  src/app/core/schemas.py
  src/app/core/security.py
  src/app/core/utils/rate_limit.py
  src/app/crud/crud_base.py
  src/app/models/post.py
  src/app/models/rate_limit.py
  src/app/models/tier.py
  src/app/models/user.py
  src/scripts/create_first_superuser.py
Labels: enhancement

#83 Add ruff linter
  pyproject.toml
  src/app/api/dependencies.py
  src/app/api/paginated.py
  src/app/api/v1/__init__.py
  src/app/api/v1/login.py
  src/app/api/v1/logout.py
  src/app/api/v1/posts.py
  src/app/api/v1/rate_limits.py
  src/app/api/v1/tasks.py
  src/app/api/v1/tiers.py
  src/app/api/v1/users.py
  src/app/core/config.py
  src/app/core/db/database.py
  src/app/core/db/models.py
  src/app/core/db/token_blacklist.py
  src/app/core/exceptions/http_exceptions.py
  src/app/core/logger.py
  src/app/core/schemas.py
  src/app/core/security.py
  src/app/core/setup.py
  src/app/core/utils/cache.py
  src/app/core/utils/rate_limit.py
  src/app/crud/crud_base.py
  src/app/crud/crud_posts.py
  src/app/crud/crud_rate_limit.py
  src/app/crud/crud_tier.py
  src/app/crud/crud_users.py
  src/app/crud/helper.py
  src/app/main.py
  src/app/middleware/client_cache_middleware.py
  src/app/models/post.py
  src/app/models/rate_limit.py
  src/app/models/tier.py
  src/app/models/user.py
  src/app/schemas/job.py
  src/app/schemas/post.py
  src/app/schemas/rate_limit.py
  src/app/schemas/tier.py
  src/app/schemas/user.py
  src/app/worker.py
  src/migrations/env.py
  src/scripts/create_first_superuser.py
  src/scripts/create_first_tier.py
  tests/conftest.py
  tests/helper.py
  tests/test_user.py
Labels: enhancement

#85 Added the comment and in the docs to change docker-compose.yml for migrations
  README.md
  docker-compose.yml
Labels: documentation

#86 create_tables_on_startd created, docs added
  README.md
  src/app/api/paginated.py
  src/app/api/v1/login.py
  src/app/api/v1/logout.py
  src/app/api/v1/rate_limits.py
  src/app/api/v1/tasks.py
  src/app/api/v1/tiers.py
  src/app/api/v1/users.py
  src/app/core/config.py
  src/app/core/db/database.py
  src/app/core/db/token_blacklist.py
  src/app/core/logger.py
  src/app/core/schemas.py
  src/app/core/setup.py
  src/app/core/utils/cache.py
  src/app/core/utils/rate_limit.py
  src/app/models/post.py
  src/app/models/rate_limit.py
  src/app/models/tier.py
  src/app/schemas/post.py
  src/app/schemas/rate_limit.py
  src/app/schemas/tier.py
  src/app/schemas/user.py
  src/app/worker.py
  src/scripts/create_first_superuser.py
  src/scripts/create_first_tier.py
  tests/helper.py
  tests/test_user.py
Labels: enhancement

#75 Add PGAdmin container for PostgreSQL administration and debugging
  .gitignore
  README.md
  docker-compose.yml
Labels: enhancement
