Repository benavlabs/FastAPI-boilerplate, pull requests merged in 2023-10, with the labels that each got.

#9 Redis cache
  README.md
  src/app/api/v1/login.py
  src/app/api/v1/posts.py
  src/app/api/v1/users.py
  src/app/core/cache.py
  src/app/core/config.py
  src/app/core/exceptions.py
  src/app/main.py
  src/poetry.lock
  src/pyproject.toml
  src/tests/test_user.py
Labels: enhancement

#11 App settings
  src/app/core/config.py
  src/app/core/database.py
  src/app/main.py
Labels: enhancement

#12 Client side cache
  README.md
  src/app/core/cache.py
  src/app/core/config.py
  src/app/main.py
Labels: enhancement

#14 Arq queue
  README.md
  src/app/api/v1/__init__.py
  src/app/api/v1/tasks.py
  src/app/api/v1/users.py
  src/app/core/config.py
  src/app/core/queue.py
  src/app/main.py
  src/app/schemas/job.py
  src/app/worker.py
  src/pyproject.toml
Labels: enhancement

#20 docker compose now working
  Dockerfile
  README.md
  docker-compose.yml
  src/app/core/config.py
  src/app/main.py
  src/scripts/__init__.py
  src/tests/conftest.py
  src/tests/helper.py
  src/tests/test_user.py
Labels: enhancement

#22 todo list added to docs
  README.md
Labels: documentation

#23 update: remove lock file also add it in git ignore
  .gitignore
  src/poetry.lock
Labels: enhancement

#24 Update README.md
  README.md
Labels: documentation

#25 Update README.md
  README.md
Labels: documentation

#26 Password hidden docs
  README.md
  src/app/core/config.py
  src/app/main.py
Labels: documentation, enhancement

#27 threadpool options, bug fixes
  src/app/main.py
Labels: bug, enhancement

#28 Minor changes
  README.md
  src/app/core/config.py
  src/app/core/setup.py
  src/app/main.py
  src/pyproject.toml
Labels: documentation, enhancement
