Repository benavlabs/FastAPI-boilerplate, pull requests merged in 2024-02, with the labels that each got.

#112 upgrade python multipart, fastapi, fastcrud
  pyproject.toml
Labels: enhancement

#114 Lifespan Events, Libs bumped, .env fix
  docker-compose.yml
  pyproject.toml
  src/app/core/setup.py
Labels: bug, enhancement

#116 fastcrud bumped to 0.6.0
  pyproject.toml
Labels: enhancement

#115 Fix default.conf spelling
  README.md
Labels: documentation

#118 bug: fix missing router when creating application
  src/app/core/setup.py
Labels: bug

#121 logging added to scripts, get_db fix, endpoints fixed for fastcrud usage
  src/app/api/v1/posts.py
  src/app/api/v1/rate_limits.py
  src/app/api/v1/tiers.py
  src/app/api/v1/users.py
  src/app/core/db/database.py
  src/scripts/create_first_superuser.py
  src/scripts/create_first_tier.py
Labels: bug, enhancement

#122 README.md broken link fix
  README.md
Labels: documentation

#123 Fastcrud paginated
  README.md
  pyproject.toml
  src/app/api/paginated.py
  src/app/api/v1/login.py
  src/app/api/v1/posts.py
  src/app/api/v1/rate_limits.py
  src/app/api/v1/tiers.py
  src/app/api/v1/users.py
Labels: enhancement
