Repository benavlabs/FastAPI-boilerplate, pull requests merged in 2024-01, with the labels that each got.

#90 Removed deprecated typing classes and replaced with native Python dict, list, type, etc.
  src/app/api/paginated.py
  src/app/api/v1/login.py
  src/app/api/v1/logout.py
  src/app/api/v1/posts.py
  src/app/api/v1/rate_limits.py
  src/app/api/v1/tasks.py
  src/app/api/v1/tiers.py
  src/app/api/v1/users.py
  src/app/core/security.py
  src/app/core/setup.py
  src/app/core/utils/cache.py
  src/app/crud/crud_base.py
  src/app/crud/helper.py
Labels: bug

#92 add pre-commit configs
  .pre-commit-config.yaml
  README.md
  default.conf
  docker-compose.yml
  mypy.ini
  src/app/api/dependencies.py
  src/app/api/paginated.py
  src/app/api/v1/tasks.py
  src/app/core/security.py
  src/app/core/setup.py
  src/app/core/utils/cache.py
  src/app/crud/crud_base.py
  src/app/crud/helper.py
  src/app/middleware/client_cache_middleware.py
  src/app/models/post.py
  src/app/models/rate_limit.py
  src/app/models/tier.py
  src/app/models/user.py
  src/app/schemas/user.py
  src/migrations/README
  src/migrations/env.py
Labels: enhancement

#97 Move worker script
  README.md
  docker-compose.yml
  src/app/core/worker/__init__.py
  src/app/core/worker/functions.py
  src/app/core/worker/settings.py
Labels: enhancement

#99 Fix for get task endpoint bug
  src/app/api/v1/tasks.py
Labels: bug

#101 Fix of pyproject.toml
  pyproject.toml
Labels: enhancement

#102 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#103 Update issue templates
  .github/ISSUE_TEMPLATE/fastapi-boilerplate-feature-request.md
  .github/ISSUE_TEMPLATE/fastapi-boilerplate-issue.md
Labels: documentation

#104 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#105 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#106 Create PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#107 Update README.md
  README.md
Labels: documentation

#109 Fast crud
  README.md
  pyproject.toml
  src/app/api/v1/posts.py
  src/app/api/v1/rate_limits.py
  src/app/api/v1/tiers.py
  src/app/api/v1/users.py
  src/app/core/db/crud_token_blacklist.py
  src/app/core/exceptions/http_exceptions.py
  src/app/core/worker/functions.py
  src/app/core/worker/settings.py
  src/app/crud/crud_base.py
  src/app/crud/crud_posts.py
  src/app/crud/crud_rate_limit.py
  src/app/crud/crud_tier.py
  src/app/crud/crud_users.py
  src/app/crud/helper.py
Labels: enhancement

#110 Update README.md
  README.md
Labels: documentation
